### PR TITLE
Bootstrap Dev VM

### PR DESCRIPTION
**Pull request by fwilhe**
This PR adds an initial implementation of a dev vm image for Garden Linux. It's built from the debian trixie repos, both for amd64 and arm64. It provides an image made for running with 'raw' QEMU and one for [lima-vm](https://lima-vm.io/).

### CODE REVIEW

**Comment by ghost** [comment]
@fwilhe Thank you for your contribution.

**Comment by fwilhe** [comment]
This Pr is affected by [this issue](https://github.com/gardenlinux/builder/issues/54)

**Comment by Vincinator** [comment]
Testing now. Readme Looks very good 🚀

**Review by Vincinator — APPROVED** [review]
LGTM

**Pull request merged**
