### PR TITLE
Add kernel-dev feature for kernel maintanance

### PR DESCRIPTION
**Pull request by Vincinator**
- Bundles packages required to execute [prepare-orig](https://gitlab.com/gardenlinux/gardenlinux-package-linux-6.6/-/blob/main/prepare-orig?ref_type=heads) 📦
    - prepare-orig generates debian kernel sources based on a upstream branch from linux 🐧
- build dependencies for kernel build
- dkms packages

- [suggested-by @fwilhe] added kerneldev builds into CI

### CODE REVIEW

**Comment by fwilhe** [comment]
Should we add this to the ci? Maybe even as a matrix build? I know this brings us closer to combinatoric explosion issues, and we need to choose wisely how many variants to build.
Maybe there could also be a way to limit CI to features that have actually been modified for PR builds.. Not sure, never done that before.

**Comment by Vincinator** [comment]
> Should we add this to the ci? 

Yes, good idea! 

Another Question: 
This PR adds `kernel-dev` feature, which depends on `dev` feature. Maybe it makes sense to move some packages from `kernel-dev` to `dev` feature?  Fully merge it into dev? 

Packages like `rsync`, `devscripts` or `xz-utils` may be good candidates for the more general `dev` feature

**Comment by Vincinator** [comment]
Not sure if we want to build kerneldev and dev flavours.
Idea: we keep `dev` feature, but only have kerneldev in the build targets. Potential future flavours could still base on dev (e.g. some dev environment with X)

**Comment by fwilhe** [comment]
> Maybe it makes sense to move some packages from kernel-dev to dev feature?

Sure. Maybe 'dev' is a poor name, considering we might have multiple 'dev' features. Maybe what I've done in 'dev' is more of a 'gl builder consumer dev' feature?

>Fully merge it into dev?

I think this might be the tradeoff between keeping the number of variants low, and having specialised images for specialised purposes. I don't really have made up my mind, but I think from a 'using this repo as a best-practice example for how to utilise the builder', we should consider the pros and cons of both approaches.

How about merging this pr as soon as we consider it working, and maybe re-structure in a follow up pr?

I could see a structure like this

```
raw | lima
---
kernel-dev | image-builder-dev
---
dev
---
base
```

Where 'dev' should have general purpose dev tooling, a container runtime and such, and then building on top of that specialised dev features.. Does that make sense? Is this in line with how the builder was intended?

Also I notice that I did not specify any dependencies between the features so far.

**Comment by Vincinator** [comment]
> Where 'dev' should have general purpose dev tooling, a container runtime and such, and then building on top of that specialised dev features.. Does that make sense? Is this in line with how the builder was intended?

That makes perfect sense to me.

**Comment by fwilhe** [comment]
Something is not right with the path for artifact upload.. guess we can also relax the regex as anyway each matrix build will only produce a single `raw` file..

Screenshot 2024-01-17 at 14 44 58

**Comment by fwilhe** [comment]
oooh, ah, its cow2 and raw, depending on which feature..

**Review by fwilhe — APPROVED** [review]
Made small adjustments to the readme and the workflow.

Looks good to me. Have not tried to run the kerneldev image.

Let's merge when CI is green and refactor/improve based on that.

**Pull request merged**
